### ISSUE TITLE
建议增加跳过大于100MB文件选项

### ISSUE THREAD

**Issue by erbanku** [Trinkle23897/learn2018-autodown#10]
由于一些课程老师上传课程录屏或者特大文件导致下载时间会延长且浪费空间，能不能在判断身份登录时让用户选择“是否下载大于100MB的文件 y/N?”,感觉这样合理一些。（知道下载过程中点击Ctrl+C跳过某文件，不过个人感觉全自动比较好，哈哈哈），望考虑一下，谢谢。

（我一直在想把这个脚本能不能通过Django or Flask做成Python Web应用，你对做成Web应用怎么看呢？）

**Comment by Trinkle23897** [comment]
web应用的话你得考虑一下用户的账号密码如何做到安全性（比如让用户确认我们不会偷偷送到某个地方或者不会停留在后端服务器上面），以及最关键一点是interactive design，如何才能做到用户体验最佳（而不是点击个download等半天然后下载zip，这就是目前wlxt助教下载学生作业的方法）
以及为啥都2021年了还用django……FastAPI不香吗

**Comment by erbanku** [comment]
**跳过大于100MB文件选项**，这个我觉得很容易实现，加几行代码就可以实现

**Comment by erbanku** [comment]
确实，出现账号安全纠纷什么的就麻烦了。

**Comment by Trinkle23897** [comment]
> **跳过大于100MB文件选项**，这个我觉得很容易实现，加几行代码就可以实现

是的，想来个pr吗？

**Comment by erbanku** [comment]
回复如此迅速，有一种使用即时通讯软件的感觉了，哈哈哈
