### ISSUE TITLE
脚本貌似出现了问题？无法执行

### ISSUE THREAD

**Issue by erbanku** [Trinkle23897/learn2018-autodown#12]
运行脚本时出现SSL证书错误`ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)` ，校园网和运营商网络都无法执行，之前一直都没什么问题的。

运行环境：Windows 11
Python版本: 3.9.7

![ShareX_2021-10-01_08-45-25](https://user-images.githubusercontent.com/79493862/135551267-996a954b-0ee7-4ff1-9322-18fe90134a69.png)

**Comment by Trinkle23897** [comment]
会不会是本地时间问题，我这边在学校服务器上面执行了下是正常的

**Comment by erbanku** [comment]
我手动修改了一下系统时间（修改为了早于今天，改成了9月29日）就执行成功了，正常时间和未来时间都不行。恐怕是网络学堂证书问题？

昨晚在树洞看到有人发下面这张图，恐怕也跟证书有关系：

![uleb3xwajuahxwenxjyxdlrtkmx6s5ed](https://user-images.githubusercontent.com/79493862/135555350-1c73e996-a77b-422e-a452-cf54dd5b7cb7.jpg)

**Comment by erbanku** [comment]
昨天开始一直没法正常运行，现在也是。除非把系统时间改为之前时间

**Comment by Trinkle23897** [comment]
https://github.com/tuna/issues/issues/1342#issuecomment-931412628

**Comment by 3verness** [comment]
求问除了调时间还有其他的解决方法么？

**Comment by Trinkle23897** [comment]
如果是windows的话看看能不能更新一下系统？linux上面是没问题的

**Comment by erbanku** [comment]
> 如果是windows的话看看能不能更新一下系统？linux上面是没问题的

目前微软没有发布带解决该证书过期的更新，我出现问题的是Win 11 beta系统，不知道Win 10 是不是也出现了这种问题。 Let's Encrypt 在官网提到已经向微软，Apple等提交了新证书（如下）。估计微软会在下一个系统更新解决。

>** ISRG Root X2 (new ECDSA root) - coming soon**
We have submitted ISRG Root X2 to the Microsoft, Apple, Google, Mozilla, and Oracle root programs for inclusion. ISRG Root X2 is already widely trusted via a cross-sign from our ISRG Root X1. For more information, check our our community forum post

**Comment by erbanku** [comment]
> 求问除了调时间还有其他的解决方法么？

微软好像今天凌晨更新证书库，把Let‘s Encrypt的最新证书（ [ISRG Root X1](https://letsencrypt.org/certificates/)）热更新更新进去了，目前应可以不改时间正常运行了，亲测我这边能正常运行。

![image](https://user-images.githubusercontent.com/79493862/135936826-f406f970-fd4c-4b5d-96f0-824f20f81db6.png)
