### ISSUE TITLE
将下载的所有东西放在 './downloads' 子目录下

### ISSUE THREAD

**Issue by FHYQ-Dong** [Trinkle23897/learn2018-autodown#21]
在git clone 您的代码到本地后如果直接运行，会在当前目录下按每个课程一个目录的方式创建n个目录。这比较影响当前目录的整洁，也不方便编写 .gitignore 文件。希望您能将下载的所有文件统一保存在某个子目录下，而不对当前目录做过多修改。

**Comment by erbanku** [comment]
Not all users save files in the downloads folder. You can move the `learn.py` file to the folder you prefer and then run it to achieve your goal. 
A pull request is not needed and may be disruptive for this. 
Please reply if you have any other questions concerned.
