### ISSUE TITLE
一些小bug和建议

### ISSUE THREAD

**Issue by AmateurZhang** [Trinkle23897/learn2018-autodown#5]
1. open 中添加 encoding = ‘UTF-8’ 以方便windows用户使用
2. path 应该replace 一些特殊字符，如/，*等
3. 强烈请求：毕业生希望更好地整理网络学堂的数据，希望在命名时加入发布时间和编号！

**Comment by Trinkle23897** [comment]
欢迎pr (x

**Comment by Trinkle23897** [comment]
@AmateurZhang 我记得我2应该replace了……？

**Comment by AmateurZhang** [comment]
replace 不够全，，老师真的会用奇奇怪怪的符号；还有能不能顺便扒一下课程信息？

**Comment by Trinkle23897** [comment]
给个测试例子？

**Comment by AmateurZhang** [comment]
老师有用/，*，“这些符号

**Comment by Trinkle23897** [comment]
/ 我escape了，*和“应该不影响使用？

**Comment by AmateurZhang** [comment]
我遇到特殊符号会报错，也许是Windows的锅？

**Comment by Trinkle23897** [comment]
update * & " & encoding
我确实没用win测过，课程信息短时间内不是很好写，如果方便的话您可以把您修好的代码pr过来，谢谢！
